### ISSUE TITLE
How to edit this code for installing gcc 9.3.0

### ISSUE THREAD

**Issue by ghost** [darrenjs/howto#3]
sir i need to run vmware on my linux but that require gcc 9.3.0 my is 32 bit architecture so how to edit this code for that??

**Comment by darrenjs** [comment]
Did you take a look at https://github.com/darrenjs/howto/blob/master/build_scripts/build_gcc_9.sh  ?  In there you can find a line that says "9.1.0",  you can try changing that to "9.3.0"
