### ISSUE TITLE
build_gcc_10 isl_tarfile wget

### ISSUE THREAD

**Issue by dimembermatt** [darrenjs/howto#4]
I was following your medium post for building gcc from source. Running the script `build_gcc_10.sh` led to a loopback connection failure upon the line (L174) `__wget ftp://gcc/gnu.org/pub/gcc/infrastructure $isl_tarfile`.

I was able to resolve this by swapping out `ftp://` with `https://`.

Thanks for your hard work!

**Comment by darrenjs** [comment]
Thanks for this feedback, I will change the script to use https.
